### ISSUE TITLE
后端包管理由 npm 切 yarn

### ISSUE THREAD

**Issue by CLDXiang** [CLDXiang/fdpink#6]
前后端保持统一吧，yarn 的指令方便一些，另外目前后端的 `package-lock.json` 里面有很多历史包袱，切换后重新 `yarn install` 看看跑不跑得起来刚好可以丢掉这些包袱

**Comment by CLDXiang** [comment]
> 现在后端有什么历史包袱啊？这都是我一个一个在开发的时候用到的时候才装上的呀

欸，我以为还在用老的，那 `class-transformer` 这个包是怎么回事？之前你是怎么装的？为啥只存在于 lock 里面？

**Comment by SunflowerAries** [comment]
我不知道欸，可能装的时候还是有些混乱吧，那就用你说的 yarn 吧，有一套规范流程之类的么？

**Comment by CLDXiang** [comment]
> 我不知道欸，可能装的时候还是有些混乱吧，那就用你说的 yarn 吧，有一套规范流程之类的么？

可能你之前装的时候直接 npm install 了，没加 --dev，用 yarn 就没关系了，装新包默认会加到 package.json 里
