### ISSUE TITLE
Editorconfig 统一开发环境

### ISSUE THREAD

**Issue by Ahacad** [CLDXiang/fdpink#8]
#2 这个 PR 到我这里 Linux 上 CRLF 全被自动替换成 LF 了，污染 commit @ichn-hu @CLDXiang

**Comment by ichn-hu** [comment]
啊不会吧，我是在 GitHub 上面编辑的呀？

**Comment by CLDXiang** [comment]
按理来说 Lunix 默认该用 LF？如果你自己想用 CRLF 的话要把 Git 全局配置改一下 `git config --global core.autocrlf true`，但 mac 和 linux 习惯上应该是用 LF 的，该配置 `git config --global core.autocrlf input`

**Comment by Ahacad** [comment]
不是，是我这里默认的 LF

**Comment by CLDXiang** [comment]
> 不是，是我这里默认的 LF，但是不知为何 pull 下来的 README 里面全是 CRLF ![2021-12-14_16-15](https://user-images.githubusercontent.com/51874356/145959241-cd735f09-0c25-4e19-9279-30d30e7e5ff8.png)

诡异，难道 Github 线上编辑默认写入 CRLF？没关系，我们默认走 LF 的，你再 commit 一次就转 LF 了

**Comment by Ahacad** [comment]
ok
